### ISSUE TITLE
Test Signature

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#11]
At the moment tests are constructed like this:

``` php
new AbTest($name, $a, $b, ParticipationStategyInterface $strategy = null);
```

where `$a` is the control variant and `$b` is the test.
What about this

``` php
/**
 * string $name
 * callable $control
 * callable|callable[] Variants
 */
new AbTest($name, $control, $variants, ParticipationStategyInterface $strategy, VariantChooserInterface $chooser);
```

Instead of `$b` an array of variations is accepted. The `AbTest` can be renamed to `Test` then.
The `$strategy` is mandatory now for every test. It's more transparent then falling back to the `Runner::$strategy`. If the `$strategy` matches the new `VariantChooserInterface` chooses the Variant to use from `$variants`.

I don't want to get object construction too complex for each test. It should be easy as possible.
Maybe we could create a Factory to generate the Tests which is aware of a default `ParticipationStategyInterface` and a default `VariantChooserInterface`.

WDYT?

**Comment by waltertamboer** [comment]
Ok so three things you suggesting:
1. Rename the `AbTest` class to `Test`. I see no problem with that.
2. Alter the signature so that an array of variations can be provided. Sounds good to me as well except for the docblock. Your docblock suggest a callable or an array of callables. I would suggest to always make it an array. Let's not make it too complicated.
3. Introduce a VariantChooserInterface. Should choosing the variant differ per test? If not than I would argue that the logic should be part of the runner.

**Comment by waltertamboer** [comment]
Actually about number 3, yes, that makes sense. The `VariantChooserInterface` should indeed be per test instance so that looks good as well.

We could indeed introduce a factory class, let's make the change first and see how we can make life easier from there on. Good suggestions!!

**Comment by HellPat** [comment]
Renaming AbTest to Test is a bigger BCbreak. I am aware that the lib may not be used in production for now. But I'd like to avoid too much API-changes in the master branch.

Should we make a develop-branch, clearify the API there, and once ready merge to master?

**Comment by waltertamboer** [comment]
I agree that we should avoid BC-breaks but we don't have a 1.0.0 release yet. At this point I don't care about BC-breaks since I much rather work towards a stable, usable release.

If it makes you feel more comfortable to introduce a develop branch than go ahead, just know that at some point we are going to introduce a BC-break since the current master is not 1.0.0 worthy. My 2 cents :)

**Comment by pachico** [comment]
I am not particularly concerned about a BC-break.
Another possibility would be to create a new organization with a new name and leave this as it is.
I have no preferences, to be honest.

**Comment by HellPat** [comment]
I'm going to add an info in the readme that this is work in progress and the API **will** change and stick with master for now.

**Comment by pachico** [comment]
I'm in favour of creating a new branch for the new joined development where we can fresh start from scratch.
0.1.x-dev, if you want.

**Comment by HellPat** [comment]
I'm okay with that.

**Comment by HellPat** [comment]
``` php
/**
 * string $name
 * callable $control
 * callable[] Variants
 */
new Test($name, $control, $variants, ParticipationStategyInterface $strategy, VariantChooserInterface $chooser);
```

Mhhh. Do we really need an extra parameter for the control-group? The control group will never do anything special. So we could just set the cookie to `_control` if the user participates in the control-group. Or am I missing something?

``` php
/**
 * string $name
 * callable[] Variants
 */
new Test($name, $variants, ParticipationStategyInterface $strategy, VariantChooserInterface $chooser);
```

**Comment by waltertamboer** [comment]
I think it's a matter of how you look at it. If you leave out the control variant, it means that the current setup will be default behaviour right?

So I have an application where I have a certain configuration. Now I want that configuration to change when my test kicks in. That means that the default configuration is the control variant and the change in configuration is the variant right? In that case you don't need the control part indeed.

Are there other use cases where you want to differ from the default setup?

**Comment by HellPat** [comment]
This PR is not needed anymore snice we're starting from scratch by defining all the interfaces.
The question is still unresolved.

> That means that the default configuration is the control variant and the change in configuration is the variant right?

Using the current configuration as one Variant (the Variant which is used for control) makes sense to me. But I'm not sure if there is an other usecase.

Maybe be should accept a control argument. This leads to this ugly array_merge because the control variant should be part of the ChooserInterface s descision for participating Users https://github.com/phpab/phpab/pull/12/files#diff-e290cdc8a86f2a5511d5472841e1e13fR110

ping @pachico

**Comment by pachico** [comment]
Control and Variant are mostly conceptual terms.
I don't see any usage for Control itself since it will be just Variant A (or 0 - BTW, I opened a question about this in the wiki).
It is also consistent with GoogleExperiments, which treats Control as 0.

**Comment by HellPat** [comment]
Okay. Let's mote this discusion to the day we're implementing it (an other issue)
