### ISSUE TITLE
Options for VariantInterface and TestInterface

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#14]
The `VariantInterface` and `TestInterface` should accept for options.
What methods should we provide.

I vote for only add one method called `getOptions`and against other methods like `getOption($option)`.

`setOption` is not needed as well because the options should not change at runtime.
Or does anyone have a scenario for that?

**Comment by pachico** [comment]
Correct, once they're set they shouldn't change and most likely will be fetched together with getOptions.

**Comment by HellPat** [comment]
@waltertamboer any concerns on your side on adding a single `getOptions()` to `TestInterface` and `VariantInterface` ?

**Comment by waltertamboer** [comment]
No concerns for only having a `getOptions()` method.

**Comment by HellPat** [comment]
At the moment we moved that to Bag so we can make it available to tests per Engine.
But we will propable need options for Variants and Test too. We will see in the implementation. Adding it will be easy.
