### ISSUE TITLE
Should StorageInterface accept string as key instead of TestInterface

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#15]
Should `StorageInterface` accept `string` as key instead of `TestInterface`?
We would be a bit more flexible with that later.

For example we could choose a naming-strategy with prefix for group based tests.

**Comment by pachico** [comment]
You mean in the constructor or in what method?

**Comment by HellPat** [comment]
All Methods in here: https://github.com/phpab/phpab/blob/master/src/Storage/StorageInterface.php#L33
and here https://github.com/pachico/abtest/blob/master/src/memory/memoryinterface.php#L25

I'm really not sure about that at all :-)

**Comment by waltertamboer** [comment]
I have no opinion about this at all, string sounds fine. The current implementation as well. If you think that a string fits better, go for it. The end user won't have to do anything with this at all since the library will handle storage.

**Comment by pachico** [comment]
Yes, probably a string would just be enough.
