### ISSUE TITLE
Enable Scruntinizer Inspections for other branches

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#16]
Is inspection for other branches than master disabled in scruntinizer? Could we enable it?

**Comment by waltertamboer** [comment]
Only the master branch was tracked, I've disabled that now so that all branches are tracked. Let's see if that works like expected.

**Comment by waltertamboer** [comment]
I've also enabled access for you guys to the Scrutinizer project.

**Comment by HellPat** [comment]
Yeaha, thanks
