### ISSUE TITLE
Does StorageInterface need a clear method?

### ISSUE THREAD

**Issue by pachico** [phpab/phpab#17]
I can't see in which case it would be useful and I see many wrong things that could happen if used.
Why would you need it?

**Comment by HellPat** [comment]
I think we need it if we the user has a Test/Variant in his Cookie and visits the Page.
The $engine->getTest($name) or $test->getOption($name) will throw an exception that is was not found.

(e.g. user removes a finished test)
We can clear the Test for future runs. The name is not perfect I think

**Comment by waltertamboer** [comment]
Can you describe the things that can go wrong?

I see one use case: Force the clearing of tests for users so you can reset settings.

**Comment by pachico** [comment]
I this case, I wouldn't reset it but create a new test. Any previous test value could simply expire or be ignored.
If you need to "reset", it means that your experiment has ended.
That means you should even provide new tracking ids.

However, I do see that it's a valid functionality (despite of what business case that might respond to) so I agree that it should be up to programmers to decide if to use it or not.
Therefore, we should keep it.
