### ISSUE TITLE
StorageInterface needs a has method

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#19]
What do you think? A bit similar to https://github.com/zendframework/zend-authentication/blob/master/src/Storage/StorageInterface.php

**Comment by waltertamboer** [comment]
has / isEmpty - A method to check if a storage entry exists.

**Comment by pachico** [comment]
Silly question, what is the entry in a cookie case? Is the cookie there at all or is there an entry for a specific test?

**Comment by waltertamboer** [comment]
In case of cookies it means: "Does the cookie exists or not?" The `has` (or insert preferred name) method  would simply check if the cookie exists.

**Comment by HellPat** [comment]
looks better.
We have to think about other cases too.
1. should there be a prefix per Engine (test can be added to multiple runners => see grouping)
2. Do we need clear method? imo no, because it clears cookies from the application, too
3. do we need isEmpty (as we can check on get() === null)
4. do we need different cookies for each test or should we use one entry per Engine and json_encode/decode the tests. => this way we are able to get all stored tests for an Engine

**Comment by pachico** [comment]
1. it won't hurt if we implement it
2. if we have more than one Engine then we shouldn't clear cookies (which I didn't think about in the first place)
3. I don't think so, it's too generic and different implementations might not require it and I don't want to force people to implement blank methods
4. We should use only one cookie. json_encode/decode is a good way to go. Later down the road we might add encryption, which is not for security for users, but to obfuscate competitors what tests a website is running.

**Comment by waltertamboer** [comment]
1. Yes - cookies should be namespaced
2. Why would it clear cookies from the application? It should only clear the cookies for the tests you want to actually clear. Like read has an identifier, clear should have an identifier as well.
3. I can live with that.
4. It's common practice to have as little cookies as possible. Cookies should also be as small as possible. That being said, I guess serializing in one cookie is perfectly fine. Maybe not JSON as it takes up too much data which is not needed. A simple separator would probably suffice.

**Comment by HellPat** [comment]
4: This is an implementation detail, which can be discussed later then. I see benefits in json because it theoretically allows nested structures (maybe needed for grouping ??)

See https://github.com/phpab/phpab/pull/26 for a first draft

**Comment by waltertamboer** [comment]
Allright, it's indeed implementation detail, doesn't really matter at this point.
