### ISSUE TITLE
Rename of namespace

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#20]
We now have namespace called Phpab\Phpab... Why is the name in there twice? It should be changed in composer.json and in code.

**Comment by waltertamboer** [comment]
Also, should it be `Phpab` or `PhpAb` ?

**Comment by pachico** [comment]
Probably was a mistake replacing from phpleague skeleton.
I don't have preferences over Phpab vs PhpAb or PhpAB.

However, it's twice because I do see Phpab as a vendor that will provide more packages/modules where the main package is called PhpAb too (unless we want to call it differently, which I don't think it's a good idea).

**Comment by pachico** [comment]
I mean, I see in the feature something like
PhpAb/PhpAb - Core
PhpAb/ModuleLaravel -- blah 
PhpAb/VariantChooserRedis -- blah

All packages that would be suggested via composer (as in https://github.com/thephpleague/flysystem/blob/master/composer.json)

**Comment by HellPat** [comment]
My intention was to follow the packagist suggested pattern `{vendor}/{package}` to allow `phpab/namecollideswithnamespaceinmainpackage` in the future. But maybe this is not needed (but i don't care cause my IDE kicks ass :-))

But I am :-1:  for `PhpAB`. Normally abbrevations should be uppercase. But PHP is an abbrevation or name, too (or isn't, I don't know, but its uppercase on http://php.net/) so we would have to use `PHPAB`. It's a bit ugly (or isn't it)?

**Comment by pachico** [comment]
PHPAB makes my eyes sad :(

**Comment by waltertamboer** [comment]
Yeah, same here :) All good with `PhpAb`?

**Comment by pachico** [comment]
I'm happy with PhpAb. Yup.

**Comment by HellPat** [comment]
Single or double?

**Comment by HellPat** [comment]
fixed
