### ISSUE TITLE
scuntinizer php-coverage

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#31]
I think this is a configuration problem and I don't know scruntinizer that well.
Why is no coverage generated and shown? Any ideas?

**Comment by waltertamboer** [comment]
How it's generated is described here https://scrutinizer-ci.com/docs/build/code_coverage

I'll look into this later today.

**Comment by waltertamboer** [comment]
The name of the config file was wrong. The file was called ".scruntinizer.yml" but it should be ".scrutinizer.yml". Fixed this in #33

**Comment by waltertamboer** [comment]
One more problem that needs to be solved:

> Scrutinizer was notified that the tests failed.
> 
> If you are sending coverage for multiple environments, make sure that all environments
> support generating code coverage, otherwise the first build that finishes
> defines the final status.

**Comment by HellPat** [comment]
I would never have found that typo. Thx.
And the badges in the Readme are always masterbranch

**Comment by waltertamboer** [comment]
PR is done and can be reviewed, I've assigned #33 to you @psren
