### ISSUE TITLE
Implementation for Interface

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#35]
# Interfaces

**Merged items will be strikedthrougt, items with PR will be checked**

Only first implementations are listed here.
More implementations will come. Maybe here in the lib or specific for the bridges.
## Final
- [ ] EngineInterface
  - [ ] Engine
- [x] ~~FilterInterface~~
  - [x] ~~PercentageFilter~~
- [x] ~~StorageInterface~~
  - [x] ~~CookieStorage~~
  - [x] ~~SessionStorage~~
  - [x] ~~RuntimeStorage (a.k.a. nothing will be persisted and it's available for the current request only)~~
- [x] ~~TestInterface~~
  - [x] ~~Test~~
- [x] ~~VariantInterface~~
  - [x] ~~CallbackVariant~~
  - [x] ~~SimpleVariant (only with name)~~
- [x] ~~ChooserInterface~~
  - [x] ~~RandomChooser~~
- [x] ~~EventDispatcherInterface~~
  - [x] ~~EventDispatcher~~
- [x] ~~EventSubscriberInterface~~
  - [x] ~~EventSubscriber~~
- [x] ~~ParticipationManagerInterface~~
  - [x] ~~ParicipationManager~~
## Abandoned
- ~~AnalyticsInterface~~

**Comment by HellPat** [comment]
I only listed implementations which go into the core lib.
Framework specific ones will be added later.

wip-interfaces have no implementations listed yet

**Comment by HellPat** [comment]
I'm starting with RandomChooser

**Comment by waltertamboer** [comment]
I'm taking the session storage

**Comment by pachico** [comment]
Let me apply the changes we discussed about EngineInterface, then

**Comment by HellPat** [comment]
I will take LotteryFilter next

**Comment by waltertamboer** [comment]
I'll create a cookie storage next.

**Comment by HellPat** [comment]
SimpleVariant goes next

**Comment by waltertamboer** [comment]
@psren What is SimpleStorage? The runtime storage?

**Comment by waltertamboer** [comment]
I'm working on the Test implementation

**Comment by HellPat** [comment]
@waltertamboer It was a stupid late night mistake. I wanted to write "SimpleVariant"

**Comment by waltertamboer** [comment]
Ok, than I'll continue with the RuntimeStorage :)

**Comment by HellPat** [comment]
haha we're making good progress :-)

**Comment by waltertamboer** [comment]
Everything has been done, I'm closing this issue.
