### ISSUE TITLE
Hook up PHP Code Sniffer in Travis

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#43]
The code style is not properly checked now. Travis should fail when the code style is not valid.

**Comment by pachico** [comment]
Is there something I can do about it? I'm not familiar with it, I'm afraid.

**Comment by waltertamboer** [comment]
It's basically like described here:
https://github.com/thephpleague/skeleton/blob/master/.travis.yml#L23

**Comment by HellPat** [comment]
You can use the automatic fixer, too with `vendor/bin/phpcbf --standard=psr2 src/ example/ test/` on your local machine.

**Comment by HellPat** [comment]
It's in
