### ISSUE TITLE
php-mock-phpunit

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#46]
There is an extensions for php-mock for php-unit.
https://github.com/php-mock/php-mock-phpunit

We should use that and implement the trait in out test. It's less error prone, since
we need to manually disable the functions in tearDown.

**Comment by pachico** [comment]
I tried it but it didn't work all the times as expected.

**Comment by HellPat** [comment]
Ah okay. I will try it an other day.

**Comment by pachico** [comment]
I think we can close this one for the moment until we want to revise the entire testing platform (if required)
