### ISSUE TITLE
Introduce webmozart/assert

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#47]
https://github.com/webmozart/assert

I've seen that we're implementing certain checks like is_string, etc. Maybe we should use this library to check preconditions.

What do you think?

**Comment by HellPat** [comment]
I'd be okay with that :+1:

**Comment by pachico** [comment]
Looks good to me

**Comment by pachico** [comment]
I integrated it for GAnalytics and will implement it in Cookie

**Comment by waltertamboer** [comment]
The library has been added as a dependency, we should just use it at the correct places. I'm closing this issue and we can create new issues for places where code needs be changed.
