### ISSUE TITLE
Session storage: why to force to have a started session?

### ISSUE THREAD

**Issue by pachico** [phpab/phpab#60]
When Session storage is created, its constructor checks for the sessions to have been previously started.
This is why you @psren saw an error, I think.
I'm wondering why is this a requirement.

@waltertamboer , can't we just start it if it hasn't?

**Comment by waltertamboer** [comment]
The requirement is there because sessions have to be started before the storage is used. I guess we can just start them if they haven't been started yes.

**Comment by pachico** [comment]
Cool, if we do that, then it will work out of the box.

**Comment by pachico** [comment]
Applied in PR.
