### ISSUE TITLE
Merge to master and tag 0.1.0

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#65]
As far as I know the branch 0.1.x-dev is ready to be merged to master.

**Comment by HellPat** [comment]
yep. I would do that, since it is usable from now.
We can tag 0.1.0 later (i am against tagging before we have at least some docs)

**Comment by pachico** [comment]
I agree with y'all.

**Comment by waltertamboer** [comment]
I did tag 0.1.0 to maintain the old code. After that tag I merged the branch to master so there is no tag for the new code yet. I did want to create the 0.1.0 tag because you'll never know who is using the current code. In order to give them the option to keep using it, the tag makes sense.
