### ISSUE TITLE
MongoDB Analytics

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#72]
It would be nice if analytics could be stored in a MongoDB database.

Relates to #71

**Comment by HellPat** [comment]
I thing we should pick an abstraction layer for that. e.g. doctrine/dbal which can handle both here.

**Comment by pachico** [comment]
Good idea, and we should define a way to assign a user identification.
GAnalytics does it behind the scenes, but if you want to do your own analytics you have to be able to track a user's behaviour.
I usually do this in these two ways:
- User is logged in: his user id (and this is up to the implementor to inject it)
- User is not logged in: I create a user identifier, store it in non-expiring cookie, and use it.

**Comment by HellPat** [comment]
@pachico you're aproach seems legit to me. I do not want to overabstract this.
So maybe the `{Mongo/MySql}DatabaseAnalytics` could have a `$analytics->store($userId)`.
I don't think we need a UserInterface or sth like that here and leave that up to the implementing developer which integrates it.

**Comment by pachico** [comment]
Pull request is here:
https://github.com/phpab/analytics-mongodb/pull/2
