### ISSUE TITLE
EngineLockedException is never used.

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#79]
Why is it in the code base? Should we sitll implement this somewhere or can it be removed?

**Comment by HellPat** [comment]
I thought that we should lock the engine if it has ran before. New tests cannot be added after that.
But Im not sure about it anymore. We can leave that problem to userland. What do you think?

**Comment by pachico** [comment]
I think it's a good idea to block it, else results might be unexpected.

**Comment by HellPat** [comment]
Closed, since merged in.
