### ISSUE TITLE
No filter set

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#80]
The current implementation allows it to add a test without passing a filter. At the same time it's also possible to skip the default filter.

This results in the creation of Bag where a null value is passed as a filter. This gives a catchable fatal error.

My suggestion: We build a check to see if either one of the values is set, if not, we throw an exception.

**Comment by waltertamboer** [comment]
Specifically:
- https://github.com/phpab/phpab/blob/master/src/Engine/Engine.php#L53
- https://github.com/phpab/phpab/blob/master/src/Engine/Engine.php#L94

**Comment by HellPat** [comment]
Same was for the chooser, too. Both ones fixed in the Merge-Request.
Please review&merge
