### ISSUE TITLE
phpDocumentor always in root folder vs in vendor/bin only in development environment

### ISSUE THREAD

**Issue by pachico** [phpab/phpab#84]
Following the conversation:
Mariano Benítez Mulet @pachico 12:29

> Hi, guys. Is it a good practice to include phpDocumentor? Shouldn't that belong to requiere-dev?

Walter Tamboer @waltertamboer 14:06

> My colleque is in the core team of phpDocumentor, according to him using the phar is the recommended way

Mariano Benítez Mulet @pachico 17:57

> it's not clear to me why it's the recommended way but I'm sure there might be reasons why the phar works better than the lib.
> Anyhow, I'm speaking about what a non-development package should include.
> If the .phar is the way to go, then I'd use a composer script that, only in dev, will download the phar inside /vendor/bin/ where all bins are.

I have come up with a proposal.
Composer doesn't have the distinction between dev and no-dev for scripts, but there are libraries that add it.
So, my idea is that in case it's dev:
- Include the lib that teaches composer to distinguish between dev and no dev
- include a dev only script that will copy phpDocumentor in vendor/bin.

It works like this:

``` json
"require-dev": {
        "scrutinizer/ocular": "^1.3",
        "phpunit/phpunit": "4.*",
        "squizlabs/php_codesniffer": "^2.5",
        "php-mock/php-mock": "^1.0",
        "zendframework/zend-eventmanager": "^3.0",
        "symfony/event-dispatcher": "^3.0",
        "neronmoon/scriptsdev": "dev-master"
    },
    "scripts-dev": {
        "post-update-cmd": [
            "php -r \"file_put_contents(__DIR__.'/vendor/bin/phpDocumentor.phar', fopen('http://phpdoc.org/phpDocumentor.phar', 'r'));\""
        ]
    },
```

If you like the approach, I'll prepare a PR with it.

**Comment by waltertamboer** [comment]
Seems useful :+1:

**Comment by pachico** [comment]
For consistency, then, we could save it as "phpDocumentor" without the ".phar" but it's just cosmetic.

**Comment by pachico** [comment]
Checking at https://getcomposer.org/doc/articles/scripts.md#package-events, it might be good to trigger the script only after post-package-install and probably have another one to delete it (if present) after post-package-uninstall.
@waltertamboer , what do you think?

**Comment by waltertamboer** [comment]
Does that mean it will download the phar after each package? That does not seem right.

**Comment by waltertamboer** [comment]
I would say that `pre-install-cmd` and `post-install-cmd` will do.

**Comment by pachico** [comment]
Cool, I'll prepare both scripts today, then, and do the PR.

**Comment by pachico** [comment]
I think we should revise this.
phpDocumentor and apigen don't seem to work in php7 (yet?) and I don't feel comfortable having things that don't work in versions we claim to support.
Considering documentation will be published in http://phpab.github.io I'd take it out of this package and include it there.

**Comment by waltertamboer** [comment]
Yes, I think this is a good idea! I'll close this issue and setup the build process in phpab/phpab.github.io
