### ISSUE TITLE
Cleanup participates method

### ISSUE THREAD

**Issue by HellPat** [phpab/phpab#87]
https://github.com/phpab/phpab/blob/master/src/Engine/Engine.php#L167

> Walter Tamboer @waltertamboer Apr. 23 15:25
> My bad, it was a mistake in the code. the participates method returns:
> false when the user is not participating
> true when the variant is null
> the name of the variant that is participating.
> I find this a bit strange. Why do we need to return the name of the variant in a function that checks (bool) if the user is participating?

The method could be split in 3 other methods.

```
participatesTest($test)
```

```
participatesTestVariant($test, $variant)
```

```
participationBlocked($test)
```

(see https://github.com/phpab/phpab/blob/master/src/Engine/Engine.php#L167)

WDYT? Isn't this a bit too fuzzy?

**Comment by waltertamboer** [comment]
I don't think your suggestion is too fuzzy. It makes sense to me. Why is it needed to return the name of the variant? Because we can also simply remove that and leave the rest as-is.

**Comment by HellPat** [comment]
So then

``` php
participatesTest($test) : bool
```

``` php
participatesTestVariant($test, $variant) : bool
```

``` php
participationBlocked($test) : bool
```

**Comment by waltertamboer** [comment]
Well, can you give me an answer first to my question? :-) Why is it needed to return the name of the variant?

**Comment by HellPat** [comment]
It is not. Normally. I just have to check for the "blocked" somehow.
So the ``variant === null`. We could fix this with an extra method.

**Comment by waltertamboer** [comment]
Than we might make it more clear by simply removing that return statement. Or do you still prefer the separate methods? I don't mind either way, the methods look fine to me.

**Comment by HellPat** [comment]
Okay, i will tackle that with two methods.

``` php
participates($test, $variant) : bool
```

and

``` php
participationBlocked($test) : bool
```

**Comment by HellPat** [comment]
sorry, was off a bit. Will tackle this one today.

**Comment by HellPat** [comment]
Mhhh, i played around a bit but wasn't able to get this into shape... could you maybe take a look @waltertamboer ?

**Comment by waltertamboer** [comment]
I'll pick this up now.
