### ISSUE TITLE
Integration with pachico/abtest

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#9]
Mariano from https://github.com/pachico/abtest has contacted me with the proposal to join forces. This seems like a good idea since his library contains certain functionality that we can nicely integrate into phpab. Also, why work on two libraries while we can make one great library.

We had a chat on IRC and came up with a plan that we will write up what the direction should be of the library. I've enabled the wiki and created some pages to document things.

Some things we agree on:
- This library should follow the PSR guidelines. Meaning PSR-1 and PSR-2 for code style and PSR-4 for autoloading.
- This library should aim for 100% unit testing code coverage.

I'm creating this issue so that everybody is informed. For questions or comments please reply to this issue.

**Comment by waltertamboer** [comment]
@psren It's clear that you have a strong opinion and it's very much valued so please share your thoughts and ideas so we can make a great library :)

**Comment by pachico** [comment]
Thanks for the summary, @waltertamboer.
I think, if we combine forces, we could create the ultimate ab test library.
We want it to be not only to be elegant but functional, capable of solving daily necessities, with built-in functionality for most common cases, but also capable of injecting new functionality.

@psren, I hope to see you on-board!

Cheers!

**Comment by HellPat** [comment]
@pachico cool :-) I look forward to this and have some time in the next weeks as i will need a strong testing lib for work.

**Comment by HellPat** [comment]
I started with some notes here https://github.com/phpab/phpab/wiki/Roadmap
Would be cool if you all add your comments and your additions there :-)

After that we can talk about the points and i think we have to talk about naming, too ;-)

**Comment by waltertamboer** [comment]
I have added my comments to the Roadmap.

**Comment by pachico** [comment]
Just added some stuff.
BTW, @psren, we created https://gitter.im/phpab to keep in touch (it works fine in mobile) until something better comes up.

Cheers

**Comment by HellPat** [comment]
I'm closing this as we're not "integrating". We're stealing the features we need :-) We all know the lib and take inspiration from there
