### ISSUE TITLE
Namespace Cleanup

### ISSUE THREAD

**Issue by waltertamboer** [phpab/phpab#91]
The last couple of days I've been working on the Zend Framework 2 module and I noticed that the namespaces we have right now don't always make sense. I think we can make things more logical which will give a more clean feeling of the library. The areas I'm talking about are analytics participation and variants.
## Analytics

We now have these classes:
- _PhpAb\Analytics\DB_
  - `PhpAb\Analytics\DB\DataCollector`
- _PhpAb\Analytics\Google_
  - `PhpAb\Analytics\Google\DataCollector`
- _PhpAb\Analytics\Renderer_
  - `PhpAb\Analytics\Renderer\AbstractGoogleAnalytics`
  - `PhpAb\Analytics\Renderer\GoogleClassicAnalytics`
  - `PhpAb\Analytics\Renderer\GoogleUniversalAnalytics`
  - `PhpAb\Analytics\Renderer\RendererInterface`

I want to suggest we change that to:
- _PhpAb\Analytics\DataCollector_
  - `PhpAb\Analytics\DataCollector\Database` (note the class rename from DB to Database)
  - `PhpAb\Analytics\DataCollector\Google`
- _PhpAb\Analytics\Renderer_
  - `PhpAb\Analytics\Renderer\RendererInterface`
  - _PhpAb\Analytics\Renderer\Google_
    - `PhpAb\Analytics\Renderer\AbstractGoogleAnalytics`
    - `PhpAb\Analytics\Renderer\GoogleClassicAnalytics`
    - `PhpAb\Analytics\Renderer\GoogleUniversalAnalytics`

Related suggestions:
- Let's move `PhpAb\Analytics\DataCollector\Database` to the `analytics-pdo` and `analytics-mongodb` packages. It has no purpose at this moment in this library.
- Let's introduce a `analytics-google` package and move the google related classes there.
## Participation

The purpose of the namespaces is to group objects that semantically belong to each other. Right now we mangle filter classes and the management classes.

There for I would like to make the following suggestion. We currently have the following classes:
- `PhpAb\Participation\FilterInterface`
- `PhpAb\Participation\Manager`
- `PhpAb\Participation\ParticipationManagerInterface`
- `PhpAb\Participation\PercentageFilter`

I would like to introduce a subnamespace called `Filter` and thus change this to:
- _PhpAb\Participation\Filter_
  - `PhpAb\Participation\Filter\FilterInterface`
  - `PhpAb\Participation\Filter\Percentage` (name change, no need to have Filter in the name twice, it's already in the namespace)
- `PhpAb\Participation\Manager`
- `PhpAb\Participation\ManagerInterface` (name change from ParticipationManagerInterface to ManagerInterface, why do we have a "Manager" and a "ParticipationManagerInterface" - it makes no sense).
## Variant

The same argument as for Participations applies here. We now have:
- `PhpAb\Variant\CallbackVariant`
- `PhpAb\Variant\ChooserInterface`
- `PhpAb\Variant\RandomChooser`
- `PhpAb\Variant\SimpleVariant`
- `PhpAb\Variant\StaticChooser`
- `PhpAb\Variant\VariantInterface`

We have mangled the variants and the choosing mechanism with each other. Therefor I would like to introduce a subnamespace called `Chooser`. This will give use the following structure:
- _PhpAb\Variant\Chooser_
  - `PhpAb\Variant\Chooser\ChooserInterface`
  - `PhpAb\Variant\Chooser\RandomChooser`
  - `PhpAb\Variant\Chooser\StaticChooser`
- `PhpAb\Variant\CallbackVariant` (Variant is in the FQCN twice, but callback is a reserved keyword)
- `PhpAb\Variant\Simple` (name change, no need to have _Variant_ in the FQCN twice)
- `PhpAb\Variant\VariantInterface`

**Comment by pachico** [comment]
I agree with everything except:
- PhpAb\Analytics\DataCollector\Database could be named as PhpAb\Analytics\DataCollector\Generic because that's what it is and it happens to be used for database analytics. Having said so, I wouldn't move it out from the core since it could be used by all sort of implementations except Analytics (because it requires the variant index)
- Google Analytics will be, I reckon, the most used analytics favour. I wouldn't have it outside the core unless we specify it as requirement in composer.

**Comment by waltertamboer** [comment]
Thanks for your feedback @pachico ! I like your suggestion to rename to Generic. It makes sense.
Let's leave Google Analytics as-is. We can always move it out later if we decide it would be better. That won't be a BC break. :+1:
